apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo-chart.labels" . | nindent 4 }}
data:
  DATABASE_NAME: "{{ .Values.configmap.dbname }}"
  DJANGO_DEBUG: "{{ .Values.configmap.debug }}"
