apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "demo-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "demo-chart.labels" . | nindent 4 }}
  annotations:
spec:
  encryptedData:
  {{- range $key, $val := .Values.secrets }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ include "demo-chart.fullname" . }}
      namespace: {{ .Release.Namespace }}
