name: devsu-assesment-ci

on:
  push:
    branches: [ dev ]

jobs:
  build:
    name: GitOps workflow
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.3'
    
    - name: Install dependencies
      run: |
        cat ./req_unittest.txt ./demo-devops-python/requirements.txt > ./demo-devops-python/req.txt
        pip install -r ./demo-devops-python/req.txt

    - name: Unit test
      run: |
        cd ./demo-devops-python
        pytest --cov=./api
