name: devsu-assesment-ci

on:
  push:
    branches: [ dev ]

jobs:
  build:
    name: GitOps workflow
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.3'

    - name: Install dependencies
      run: |
        pip install -r ./src/requirements.txt -r ./src/req_unittest.txt

    - name: Unit test
      run: |
        cd ./src
        tox -e py
        cd ..

    - name: Override path in coverage report
      run: sed -i "s/<source>\/home\/runner\/work\/devsu-devops-assessment\/devsu-devops-assessment\/src\/api<\/source>/<source>\/github\/workspace\/src\/api<\/source>/g" /home/runner/work/devsu-devops-assessment/devsu-devops-assessment/src/coverage.xml

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.SONAR_GITHUB }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
